name: Gunluk TEIAS Raporu Gonderici

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build-and-send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v3

      - name: Stabil Google Chrome ve Sürücüsünü Kur
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      # === YENİ KONTROL ADIMI ===
      - name: Kurulum Yollarını Kontrol Et
        run: |
          echo "Chrome Path Logu: ${{ steps.setup-chrome.outputs.chrome-path }}"
          echo "ChromeDriver Path Logu: ${{ steps.setup-chrome.outputs.chromedriver-path }}"

      - name: Python 3.9 Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Raporu İndir ve E-posta Gönder
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          CHROMEDRIVER_PATH_ENV: ${{ steps.setup-chrome.outputs.chromedriver-path }}
        run: python ytb_github_gunluk_mail_atan.py