name: Gunluk TEIAS Raporu Gonderici

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build-and-send-report:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Kopyala
      uses: actions/checkout@v3

    - name: Python 3.9 Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Gerekli Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Raporu İndir ve E-posta Gönder
      run: |
        python rapor_indirici_epostali.py