name: Gunluk TEIAS Raporu Gonderici

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # Her gün UTC saatiyle 05:00'de (Türkiye saatiyle 08:00)

jobs:
  build-and-send-report:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Kopyala
      uses: actions/checkout@v3

    # Bu adım, sanal sunucuya stabil bir Chrome kurar
    - name: Stabil Google Chrome Kurulumu
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Python 3.9 Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Gerekli Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Raporu İndir ve E-posta Gönder
      env:
        GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        python ytb_github_gunluk_mail_atan.py